version: "3.7"

services:
  # Proxy
  proxy:
    build: ./proxy
    depends_on:
      - frontend
      - openmrs
    ports:
      - 80:80

  # Frontend
  frontend:
    build: ./ui
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
    volumes:
      - ./distro/spa:/usr/share/nginx/html/

  # OpenMRS:
  openmrs:
    build: openmrs/
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_CONFIG_CONNECTION_SERVER: host.docker.internal
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs_working
      OMRS_CONFIG_CONNECTION_USERNAME: ${OPENMRS_DB_USER}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OPENMRS_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data
      - ./distro/openmrs_core/:/openmrs/distribution/openmrs_core/
      - ./distro/openmrs_modules:/openmrs/distribution/openmrs_modules/
      - ./distro/openmrs_config:/openmrs/distribution/openmrs_config/

volumes:
  openmrs-data: ~
